import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Sidebar } from "@/components/Sidebar";
import { ParticlesBackground } from "@/components/ParticlesBackground";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased dark`}
    >
      <body className="h-full flex bg-slate-950 text-slate-50 overflow-hidden relative">
        <ParticlesBackground />
        <Sidebar />
        <main className="flex-1 overflow-y-auto p-8 relative z-10 bg-slate-950/60 backdrop-blur-sm">
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-blue-900/10 via-transparent to-transparent -z-10 pointer-events-none"></div>
          {children}
        </main>
      </body>
    </html>
  );
}
